apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-calculator
  labels:
    app: flask-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-calculator
  template:
    metadata:
      labels:
        app: flask-calculator
    spec:
      containers:
        - name: flask
          # *** Replace IMAGE_HERE with your actual image, e.g. devmalang/flask-calculator:latest
          image: devmalang/flask-calculator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
