apiVersion: v1
kind: Service
metadata:
  name: demo-nginx
spec:
  type: NodePort
  selector:
    app: demo-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort optional; Argo/cluster will assign if omitted
